version: "3.8"

services:
  mongo-orders-ms:
    image: mongo:3.6
    container_name: mongo-ms-orders
    ports:
      - "27017:27017"
    volumes:
      - mongo_order_volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345
    networks:
      - net-ms

  mongo-payments-ms:
    image: mongo:3.6
    container_name: mongo-ms-payments
    ports:
      - "27018:27017"
    volumes:
      - mongo_payment_volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345
    networks:
      - net-ms

  mongo-stores-ms:
    image: mongo:3.6
    container_name: mongo-ms-stores
    ports:
      - "27019:27017"
    volumes:
      - mongo_store_volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345
    networks:
      - net-ms

  mongo-deliveries-ms:
    image: mongo:3.6
    container_name: mongo-ms-deliveries
    ports:
      - "27020:27017"
    volumes:
      - mongo_delivery_volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345
    networks:
      - net-ms

  mongo-auths-ms:
    image: mongo:3.6
    container_name: mongo-ms-auths
    ports:
      - "27021:27017"
    volumes:
      - mongo_auth_volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345
    networks:
      - net-ms

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-broker
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 2s
    networks:
      - net-ms

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    image: img-gateway
    container_name: gateway
    ports:
      - "9000:9000"
    environment:
      - PORT=9000
      - PATH_MS_ORDER=http://orders-ms:8080
      - PATH_MS_AUTH=http://auths-ms:8079
    networks:
      - net-ms
    depends_on:
      - mongo-orders-ms
      - rabbitmq
    restart: always

  auths-ms:
    build:
      context: .
      dockerfile: auth/Dockerfile
    image: img-auths-ms
    container_name: auths-ms
    environment:
      - PORT=8079
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=12345
      - MONGO_HOST=mongo-auths-ms
      - MONGO_PORT=27017
      - MONGO_DATABASE=auth
      - MONGO_AUTH_SOURCE=admin
      - RABBITMQ_HOST=rabbitmq:5672
    networks:
      - net-ms
    depends_on:
      - mongo-auths-ms
    restart: always

  orders-ms:
    build:
      context: .
      dockerfile: orders-ms/Dockerfile
    image: img-orders-ms
    container_name: orders-ms
    environment:
      - PORT=8080
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=12345
      - MONGO_HOST=mongo-orders-ms
      - MONGO_PORT=27017
      - MONGO_DATABASE=order
      - MONGO_AUTH_SOURCE=admin
      - RABBITMQ_HOST=rabbitmq:5672
    networks:
      - net-ms
    depends_on:
      - mongo-orders-ms
      - rabbitmq
    restart: always

  payments-ms:
    build:
      context: .
      dockerfile: payments-ms/Dockerfile
    image: img-payments-ms
    container_name: payments-ms
    environment:
      - PORT=8081
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=12345
      - MONGO_HOST=mongo-payments-ms
      - MONGO_PORT=27017
      - MONGO_DATABASE=payment
      - MONGO_AUTH_SOURCE=admin
      - RABBITMQ_HOST=rabbitmq:5672
    networks:
      - net-ms
    depends_on:
      - mongo-payments-ms
      - rabbitmq
    restart: always

  stores-ms:
    build:
      context: .
      dockerfile: stores-ms/Dockerfile
    image: img-stores-ms
    container_name: stores-ms
    environment:
      - PORT=8082
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=12345
      - MONGO_HOST=mongo-stores-ms
      - MONGO_PORT=27017
      - MONGO_DATABASE=store
      - MONGO_AUTH_SOURCE=admin
      - RABBITMQ_HOST=rabbitmq:5672
    networks:
      - net-ms
    depends_on:
      - mongo-stores-ms
      - rabbitmq
    restart: always

  deliveries-ms:
    build:
      context: .
      dockerfile: deliveries-ms/Dockerfile
    image: img-deliveries-ms
    container_name: deliveries-ms
    environment:
      - PORT=8083
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=12345
      - MONGO_HOST=mongo-deliveries-ms
      - MONGO_PORT=27017
      - MONGO_DATABASE=delivery
      - MONGO_AUTH_SOURCE=admin
      - RABBITMQ_HOST=rabbitmq:5672
    networks:
      - net-ms
    depends_on:
      - mongo-deliveries-ms
      - rabbitmq
    restart: always

volumes:
  mongo_order_volume:
  mongo_payment_volume:
  mongo_store_volume:
  mongo_delivery_volume:
  mongo_auth_volume:
networks:
  net-ms:
